version: v1.0
name: Production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: "Create a new cluster"
    task:
      jobs:
      - name: New cluster
        commands:
          - echo "done"
  - name: "Deploy"
    task:
      jobs:
      - name: Deploy
        commands:
          - echo "done"
  - name: "Is it live?"
    task:
      jobs:
      - name: Test
        commands:
          - echo "done"
  - name: "Switch LB to new env"
    task:
      jobs:
      - name: LB switch
        commands:
          - echo "done"

promotions:
  - name: Remove old env after 1h
    pipeline_file: cleanup.yml
    auto_promote_on:
      - result: passed
  - name: Rollback
    pipeline_file: rollback.yml
